#!/bin/sh
#
# CVL run script for GUI applications.
#

USERHOME="$HOME"
VNCHOME="${USERHOME}/.vnc"
RUN_LOG="/usr/local/bin/cvllog.sh"
LOG_FILE="${VNCHOME}/cvlcloudstoreplus.log"

# Find the first scratch directory and set the owncloud folder to $USER under scratch

configdir="$HOME/.local/share/data/CloudStor"
owncloudDir="$HOME/.local/share/data/ownCloud"

if [ -d $configfir ]; then
    CLOUDSTORSCRATCHDIR=`grep localPath $configdir/cloudstor.cfg | cut -f2 -d "=" | rev | cut -d"/" -f2- | rev`
    ln -s ${configdir} ${owncloudDir}
else
    CLOUDSTORSCRATCHDIR=`find $HOME -maxdepth 1 -name '*scratch' -type l -print -quit` 
    CLOUDSTORSCRATCHDIR=$CLOUDSTORSCRATCHDIR/$USER
fi

if [ -f ${RUN_LOG} ]; then
    source ${RUN_LOG} ${LOG_FILE}
fi

user_email=""
module load cloudstor/2.4.2

function RunOwnCloud() {
    #VIS=/usr/local/bin/cvlvisrun
    #module load icu
    #module load qt/4.8.2
    #module load qtkeychain
    owncloud --logfile $HOME/.vnc/cloudstorplus.log --logexpire 24 &
    sleep 10 
    RV=$?
    if [ ${RV} -eq 0 ]; then
       echo "start owncloud good" 
    else
       echo "failed to run owncloud" 
    fi
}

setup_done="True"
configdir="$HOME/.local/share/data/CloudStor"
owncloudDir="$HOME/.local/share/data/ownCloud"
function SetupOwnCloud() {
    dir=$(dirname $(which owncloud-run))
    response=$(${dir}/cvl_cloudstore_setup.py -m ${dir}/setup.txt --email ${HOME}/.emailaddress)
    echo "Response = ${response}"
    if [[ ${response} == "Run" ]]; then
    	user_email=$(cat ${HOME}/.emailaddress)
        if [ -z ${user_email} ]; then
            Log "Error: empty email address" 
            setup_done="False"
            return 1 
        fi
        if [ ! -d $CLOUDSTORSCRATCHDIR/cloudstorplus ]; then
    	    mkdir -p $CLOUDSTORSCRATCHDIR/cloudstorplus
        fi
        if [ ! -d ${configdir}/folders ]; then
    	    mkdir -p ${configdir}/folders 
        fi
    	echo "[Accounts]" > ${configdir}/cloudstor.cfg
        echo "version=2" >> ${configdir}/cloudstor.cfg
    	echo "0\url=https://cloudstor.aarnet.edu.au/plus" >> ${configdir}/cloudstor.cfg
    	echo "0\http_user=${user_email}" >> ${configdir}/cloudstor.cfg
    	echo "0\authType=http" >> ${configdir}/cloudstor.cfg
    	echo "0\user=${user_email}" >> ${configdir}/cloudstor.cfg
    	echo "0\Folders\1\localPath=$CLOUDSTORSCRATCHDIR/cloudstorplus" >> ${configdir}/cloudstor.cfg
    	echo "0\Folders\1\targetPath=/" >> ${configdir}/cloudstor.cfg
    	echo "0\Folders\1\paused=false" >> ${configdir}/cloudstor.cfg
    	echo "0\Folders\1\ignoreHiddenFiles=true" >> ${configdir}/cloudstor.cfg
        ln -s ${configdir} ${owncloudDir} 
    elif [[ ${response} == "Cancel" ]]; then
        setup_done="False"
        Log "Cancel set up"
    fi
}

if [ ! -f ${configdir}/cloudstor.cfg ]; then
    #Log "Run setup"
    SetupOwnCloud
fi

owncloudProcess=$(ps -u ${USER} | grep owncloud | grep -v owncloud-run)

if [[ -z "${owncloudProcess}" && ${setup_done} == "True" ]]; then
    #Log "Run client"
    RunOwnCloud    
fi

if [[ ${setup_done} == "True" ]]; then
    #Log "Open file browser"
    nautilus --browser $CLOUDSTORSCRATCHDIR/cloudstorplus
fi
