# design diagramm https://docs.google.com/presentation/d/1ZuVz3dehaAfztqIO2s5lpsRP8zoDvN32lG5GxX3qgx8/edit#slide=id.g11e5533a82c_0_80
#doc https://docs.google.com/document/d/1uVcha_nvkUZSwxYFgYB0QgMIVWJvZSszR2e4YLZnwQ4/edit


#instructions on how to regiter a self-hosted runner
#https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners


name: container-builder-buildonpush

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  # not specifying a branch is interpreted as "trigger on any branch"  branches: [ master, githubactions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "buildonpush"
  buildonpush:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: build container
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          sudo pwd
          echo this is your branchname	$GITHUB_REF_NAME	
